spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/trello
    username: root  
    password: Macarron_3
app:
  base-url: http://localhost:8080/trello/v1/
  domain:
    success-url: http://localhost:3000/suscripcion/exito
    cancel-url: http://localhost:3000/suscripcion/fallo