spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health, info
        exclude: env
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always