spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/trello
    username: root
    password: Macarron_3
app:
  base-url: http://localhost:8080/trello/v1
  frontend-base-url: http://localhost:3000
  resend-api-key: no_disponible
  domain:
    oauth-success-url: ${app.base-url}/oauth-callback
    success-url: http://localhost:3000/suscripcion/exito
    cancel-url: http://localhost:3000/suscripcion/fallo
stripe:
  api:
    secretKey: sk_test_TU_CLAVE_SECRETA_COMPLETA_AQUI
  webhook:
    secret: whsec_TEMPORAL_SOLO_PARA_ARRANCAR