spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health, info
        exclude: env
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
app:
  base-url: http://${RAILWAY_PUBLIC_DOMAIN}/trello/v1/
  frontend-base-url: https://${WEB_TRELLO_URL}
  resend-api-key: ${RESEND_API_KEY}
  domain:
    success-url: https://${WEB_TRELLO_URL}/suscripcion/exito
    cancel-url: https://${WEB_TRELLO_URL}/suscripcion/fallo